experiment_name: grid_search_avalon_MLP_architectures

search:
  type: grid
  scoring: neg_root_mean_squared_error
  n_trials: null                          
  cv_splits: 5
  refit: true
  seed: 42
  verbose: 0  
  direction: minimize

results:
  output_path: ./results
  metric: sklearn.metrics.root_mean_squared_error
  bootstrap_on_val: true
  display_parity_plot: true
  
param_space:
  data_representation:
    Avalon_1024: {fp_name_or_path: AvalonFingerprint_1024}
  model:
    sklearn.neural_network.MLPRegressor:
      random_state: [42]
      early_stopping: [true]
      hidden_layer_sizes:
        - [512]
        - [512, 512]
        - [512, 128]
        - [256]
        - [256, 256]
        - [256, 64]
        - [128]
        - [128, 128]
        - [128, 32]
      alpha: [0.033]
      learning_rate_init: [0.00095]