experiment_name: tpe_lgbm_rdkit

data_path: ./data/logP_dataset.csv
split_info_path: ./data/split_info.json

results:
  output_path: ./results
  metric: sklearn.metrics.root_mean_squared_error
  save_search_cv_results: true
  save_best_val_results: true
  bootstrap_on_val: true
  display: true

# kwargs for PipelineConstructor
pipeline:
  regressor__model: lightgbm.LGBMRegressor
  regressor__model__kwargs:
    random_state: 42
    verbose: -1
  regressor__fp_transform__name: RDKitFingerprint_2048 # None by default, either name or path should specified
  regressor__fp_transform__base_dir: ./data     # by default
  regressor__fp_transform__path: null           # by default
  regressor__fp_transform__cash_fp: true        # by default

# kwargs for OptunaSearchCV
search:
  search_type: tpe                  # "grid", "random", "tpe"
  param_space:                      # should be specified
    regressor__model__n_estimators:
      type: int
      low: 200
      high: 1500
      log: True
    regressor__model__learning_rate:
      type: float
      low: 0.01
      high: 0.3
      log: True
    regressor__model__max_depth:
        type: int
        low: 3
        high: 10
    regressor__model__min_child_weight:
      type: int
      low: 2
      high: 20
    regressor__model__subsample:
      type: float
      low: 0.4
      high: 0.9
    regressor__model__colsample_by_tree:
      type: float
      low: 0.4
      high: 0.9
    regressor__model__gamma:
      type: float
      low: 0
      high: 1
    regressor__model__reg_alpha:
      type: float
      low: 0
      high: 5
    regressor__model__reg_lambda:
      type: float
      low: 0
      high: 10
  scoring: "neg_root_mean_squared_error"    # by default
  n_trials: 96                              
  cv_splits: 5                              # by default
  refit: true                               # by default
  seed: 42                                  # by default
  verbose: 0
  experiment_name: "unnamed_experiment"     # by default, but forced to use "experiemnt_name" value here
  direction: "minimize"                     # by default