experiment_name: tpe_search_Torch_MLP

search:
  type: tpe
  scoring: neg_root_mean_squared_error
  bootstrap_without_cv: true
  n_trials: 512                              
  cv_splits: 1
  refit: true
  seed: 42
  verbose: 0  
  direction: minimize

results:
  output_path: ./results
  metric: sklearn.metrics.root_mean_squared_error
  bootstrap_on_val: true
  display_parity_plot: true
  
param_space:
  data_representation:
    fp_1: {fp_name_or_path: AvalonFingerprint_1024}
  model:
    torch_models.FastPLMLPRegressor:
      random_state: [42]
      hidden_layer_sizes:
        - [768]
        - [768, 256]
        - [768, 256, 16]
        - [512]
        - [512, 256]
        - [512, 256, 16]
        - [128]
        - [128, 32]
        - [128, 32, 16]
      learning_rate:
        type: float
        low: 0.0001
        high: 0.1
        log: true
      weight_decay:
        type: float
        low: 0.00001
        high: 0.1
        log: true
      batch_size: [32, 64, 128, 512]
      activation: [relu, leaky_relu]
      